### ISSUE TITLE
Shape tests failing when installing ProxSuite

### ISSUE THREAD

**Issue by stephane-caron** [stephane-caron/qpsolvers#82]
When adding `proxsuite` to the test environment in ``tox.ini``, all shape tests fail simultaneously:

```
======================================================================
FAIL: test_all_shapes_cvxopt (tests.test_solve_qp.TestSolveQP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.../src/qpsolvers/tests/test_solve_qp.py", line 247, in test
    self.assertLess(norm(x - quadprog_solution), 2e-4)
AssertionError: 0.00021352703614369313 not less than 0.0002

======================================================================
FAIL: test_all_shapes_cvxpy (tests.test_solve_qp.TestSolveQP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.../src/qpsolvers/tests/test_solve_qp.py", line 247, in test
    self.assertLess(norm(x - quadprog_solution), 2e-4)
AssertionError: 456.17143090559387 not less than 0.0002

======================================================================
FAIL: test_all_shapes_ecos (tests.test_solve_qp.TestSolveQP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.../src/qpsolvers/tests/test_solve_qp.py", line 247, in test
    self.assertLess(norm(x - quadprog_solution), 2e-4)
AssertionError: 151.09703206141177 not less than 0.0002

======================================================================
FAIL: test_all_shapes_osqp (tests.test_solve_qp.TestSolveQP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.../src/qpsolvers/tests/test_solve_qp.py", line 247, in test
    self.assertLess(norm(x - quadprog_solution), 2e-4)
AssertionError: 0.00021352703614369313 not less than 0.0002

======================================================================
FAIL: test_all_shapes_proxqp (tests.test_solve_qp.TestSolveQP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.../src/qpsolvers/tests/test_solve_qp.py", line 247, in test
    self.assertLess(norm(x - quadprog_solution), 2e-4)
AssertionError: inf not less than 0.0002

======================================================================
FAIL: test_all_shapes_quadprog (tests.test_solve_qp.TestSolveQP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.../src/qpsolvers/tests/test_solve_qp.py", line 247, in test
    self.assertLess(norm(x - quadprog_solution), 2e-4)
AssertionError: 89.28461058122137 not less than 0.0002

======================================================================
FAIL: test_all_shapes_scs (tests.test_solve_qp.TestSolveQP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/.../src/qpsolvers/tests/test_solve_qp.py", line 247, in test
    self.assertLess(norm(x - quadprog_solution), 2e-4)
AssertionError: 0.7159031647958832 not less than 0.0002

----------------------------------------------------------------------
Ran 19 tests in 0.270s
```

**Comment by stephane-caron** [comment]
Fixed by https://github.com/stephane-caron/qpsolvers/commit/48178fca2a3d48f16bf47eb4029953ea648b9859, this was unrelated to ProxSuite.
